### ISSUE TITLE
Can't publish stubs; doesn't change behavior

### ISSUE THREAD

**Issue by taagaard** [atehnix/laravel-stubs#1]
I got to this stage:

`php artisan vendor:publish --provider=ATehnix\LaravelStubs\Providers\ConsoleSupportServiceProvider`

and the response was

`Nothing to publish for tag []`

At 

`php artisan stubs:publish`

the response was

`[Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "stubs" namespace. `

I figured out the intent of both those commands, and manually copied your config file into the /config directory, and manually copied .stubs files into resources/stubs. 

No dice, though. 

`php artisan make:model TestModel`

still returns a file based on the original .stub, not my lightly edited one from resources/stubs. 

I quit and restarted terminal. Dumped the composer auto-load files. I don't know what else to do.

**Comment by ghost** [comment]
I suspect that you have cached configuration. Try the command `php artisan config:clear`.

**Comment by ghost** [comment]
Let me know if the problem still exists after cleaning the cache.
Then I will know that the problem requires solving.

**Comment by taagaard** [comment]
Sorry. Still doesn't work. Let me know how I can help you track down the bug.

I'm including a screenshot, so you can verify that I've installed and configured this correctly.

<img width="886" alt="screenshot 2016-11-15 09 22 06" src="https://cloud.githubusercontent.com/assets/23218827/20315991/fd86115e-ab14-11e6-92c1-8276aa0d46e3.png">

**Comment by ghost** [comment]
Which version laravel you used?

I just checked the installation package on a fresh laravel project and could not replicate your problem. (I used Laravel 5.3.23)

Unfortunately, I have no idea what could be the reason and how can I reproduce your problem.

**Comment by taagaard** [comment]
Huh. I'm on 5.3.23 as well. I'll have a play with a clean project 
tomorrow and see if I can track down what's causing the problem.
