### ISSUE TITLE
Add missing new stubs

### ISSUE THREAD

**Issue by ghost** [atehnix/laravel-stubs#4]
In Laravel 5.4 added new stubs, which are not yet in the package:

- markdown-mail.stub (`artisan make:mail --markdown`)
- markdown-notification.stub (`artisan make:notification --markdown`)
- unit-test.stub (`artisan make:test --unit`)

**Comment by ghost** [comment]
Done.

**Comment by Kristories** [comment]
@atehnix `artisan make:view`?

**Comment by ghost** [comment]
@Kristories 

This package uses only officially available framework commands.

As far as I know, at the moment there is no such command and stubs in Laravel.

Let me know when this command becomes available in the Laravel release and I will be happy to add the appropriate stubs to the package. 
:)

**Comment by vesper8** [comment]
I'm looking for a package that does that yours does bust also allows to add custom generators for example

make:service
make:response

@atehnix 

etc.. would be nice if your package could be more flexible like that
