### ISSUE TITLE
Can't find make:migration stub

### ISSUE THREAD

**Issue by zrkb** [atehnix/laravel-stubs#7]
There are many stubs that are not in the list of Laravel `make:` commands.

Can you add them?

Regards

**Comment by ghost** [comment]
Thanks for the feedback.
When there is free time, I'll try to add missing stubs.

Please list what other stubs are missing?

**Comment by zrkb** [comment]
Hi @atehnix, the missing stubs are the following,

- `auth`
- `factory`
- `migration`
- `seeder`
- `test`

Thanks!

**Comment by ghost** [comment]
On the current version of laravel (5.6), stubs for "make:factory", "make:seeder" and "make:test" should work as expected. I now checked it. 

For older versions of Laravel, the package is distributed "as is". If some stubs in older versions are not available, then most likely they will not be added, sorry.

On the current version, stubs for "make:migration" and "make:auth" are not currently available. 
I will think about it. Thanks.

**Comment by zrkb** [comment]
Hi @atehnix,

My need is only for migration stub but I have implemented a custom solution for now.

Thanks for your quick reply.

**Comment by ghost** [comment]
@imfx In the newly released [v5.0.0](https://github.com/atehnix/laravel-stubs/releases/tag/v5.0.0) added stubs for migrations (#11) 
Better late than never... :smile:
